# Generated by Django 4.2.5 on 2023-09-25 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goalGetter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goal',
            options={'verbose_name': 'Цель', 'verbose_name_plural': 'Цели'},
        ),
    ]
