# Generated by Django 4.2.5 on 2023-09-25 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goalGetter', '0002_alter_goal_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='goalGetter.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='priority',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='goalGetter.priority', verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='goal',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='goalGetter.status', verbose_name='Статус'),
        ),
    ]
