# Generated by Django 4.2.5 on 2023-09-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goalGetter', '0003_alter_goal_category_alter_goal_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Описание'),
        ),
    ]
